# Generated by Django 5.0 on 2026-05-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('org_main', '📋 Сведения об ОО - главная'), ('org_basic', '📋 Сведения об ОО - Основные сведения'), ('org_structure', '📋 Сведения об ОО - Структура и органы управления'), ('org_documents', '📋 Сведения об ОО - Документы'), ('org_education', '📋 Сведения об ОО - Образование'), ('org_standards', '📋 Сведения об ОО - Образовательные стандарты'), ('org_management', '📋 Сведения об ОО - Руководство'), ('org_teachers', '📋 Сведения об ОО - Педагогический состав'), ('org_material', '📋 Сведения об ОО - Материально-техническое обеспечение'), ('org_accessible', '📋 Сведения об ОО - Доступная среда'), ('org_paid', '📋 Сведения об ОО - Платные образовательные услуги'), ('org_finance', '📋 Сведения об ОО - Финансово-хозяйственная деятельность'), ('org_vacancies', '📋 Сведения об ОО - Вакантные места'), ('org_scholarships', '📋 Сведения об ОО - Стипендии и меры поддержки'), ('org_international', '📋 Сведения об ОО - Международное сотрудничество'), ('org_nutrition', '📋 Сведения об ОО - Организация питания'), ('rest_main', '🏖️ Организация отдыха детей - главная'), ('rest_about', '🏖️ Организация отдыха детей - Об организации'), ('rest_activity', '🏖️ Организация отдыха детей - Деятельность'), ('rest_material', '🏖️ Организация отдыха детей - Материально-техническое обеспечение'), ('rest_services', '🏖️ Организация отдыха детей - Услуги'), ('rest_accessible', '🏖️ Организация отдыха детей - Доступная среда'), ('rest_other', '🏖️ Организация отдыха детей - Иная информация'), ('nutrition_main', '🍎 Организация питания - главная'), ('nutrition_menu', '🍎 Организация питания - Ежедневное меню'), ('security_main', '🔒 Информационная безопасность - главная'), ('security_local_acts', '🔒 Информационная безопасность - Локальные нормативные акты'), ('security_regulation', '🔒 Информационная безопасность - Нормативное регулирование'), ('security_teachers', '🔒 Информационная безопасность - Педагогам'), ('security_students', '🔒 Информационная безопасность - Обучающимся'), ('security_parents', '🔒 Информационная безопасность - Родителям'), ('security_sites', '🔒 Информационная безопасность - Безопасные сайты'), ('eduwork_main', '🎭 Воспитательная работа - главная'), ('eduwork_oop_noo', '🎭 Воспитательная работа - ООП НОО'), ('eduwork_oop_ooo', '🎭 Воспитательная работа - ООП ООО'), ('eduwork_oop_soo', '🎭 Воспитательная работа - ООП СОО'), ('eduwork_analysis', '🎭 Воспитательная работа - Анализ достижений'), ('eduwork_psychological', '🎭 Воспитательная работа - Психолого-педагогическая помощь'), ('eduwork_events', '🎭 Воспитательная работа - Общешкольные события'), ('gia_main', '📝 ГИА - главная'), ('gia_9', '📝 ГИА-9'), ('gia_11', '📝 ГИА-11'), ('monitoring_main', '📊 Мониторинг - главная'), ('monitoring_sites', '📊 Мониторинг - Сайты'), ('monitoring_fis', '📊 Мониторинг - ФИС'), ('monitoring_compliance', '📊 Мониторинг - Соответствие')], max_length=50, unique=True, verbose_name='Страница')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Поддерживается HTML-разметка', verbose_name='Содержание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Содержимое страницы',
                'verbose_name_plural': 'Содержимое страниц',
            },
        ),
    ]
