# Generated by Django 5.0 on 2026-05-03 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название раздела')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка (только латиницей)')),
                ('content', models.TextField(blank=True, help_text='Поддерживается HTML-форматирование', verbose_name='Содержание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.section', verbose_name='Родительский раздел')),
            ],
            options={
                'verbose_name': 'Раздел (Сведения об ОО)',
                'verbose_name_plural': '📄 Разделы (Сведения об образовательной организации)',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.DeleteModel(
            name='PageContent',
        ),
    ]
