# Generated by Django 5.0 on 2026-05-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_section_delete_pagecontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы (Сведения об ОО)'},
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(blank=True, help_text='Поддерживается HTML', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
