# Generated by Django 5.0 on 2026-05-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_teacher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True, help_text='Образование, достижения, стаж, награды и т.д.', null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='Фото'),
        ),
    ]
