# Generated by Django 5.0 on 2026-05-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_teacher_bio_alter_teacher_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='education_level',
            field=models.CharField(choices=[('primary', 'Начальное общее образование (1-4 классы)'), ('secondary', 'Основное и/или среднее общее образование (5-11 классы)'), ('additional', 'Дополнительное образование детей и взрослых'), ('all', 'Все уровни образования')], default='all', help_text='Укажите, на каком уровне образования работает преподаватель', max_length=20, verbose_name='Уровень образовательной программы'),
        ),
    ]
