# Generated by Django 5.0 on 2026-05-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_teacher_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='academic_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Учёное звание (при наличии)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='degree',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Учёная степень (при наличии)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='education_programs',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Образовательные программы (какие классы)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Квалификация по диплому'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='retraining',
            field=models.TextField(blank=True, null=True, verbose_name='Профессиональная переподготовка'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Преподаваемые предметы'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_experience',
            field=models.IntegerField(default=0, verbose_name='Педагогический стаж (лет)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='total_experience',
            field=models.IntegerField(default=0, verbose_name='Общий стаж работы (лет)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='training_courses',
            field=models.TextField(blank=True, null=True, verbose_name='Повышение квалификации за последние 3 года'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='education_level',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Уровень образования (диплом)'),
        ),
    ]
