# Generated by Django 5.0 on 2026-05-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_teacher_academic_title_teacher_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slides/', verbose_name='Изображение для слайда'),
        ),
    ]
