# Generated by Django 5.0 on 2026-05-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_slide_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='link',
        ),
    ]
