# Generated by Django 5.0 on 2026-05-11 14:43

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_slide_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[800, 450], upload_to='news_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[1920, 800], upload_to='slides/', verbose_name='Изображение для слайда'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[600, 800], upload_to='teachers/', verbose_name='Фото'),
        ),
    ]
