# Generated by Django 5.0 on 2026-05-12 07:56

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_news_image_alter_slide_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Содержание'),
        ),
    ]
