# Generated by Django 5.0 on 2026-05-14 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_file_field'),
        ('main', '0012_alter_section_content'),
    ]

    operations = [
    ]
