# Generated by Django 5.0 on 2026-05-14 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_merge_0002_add_file_field_0012_alter_section_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
            ],
            options={
                'verbose_name': 'Документы',
                'verbose_name_plural': 'Документы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.section',),
        ),
        migrations.CreateModel(
            name='SectionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='section_files/', verbose_name='Файл')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание файла')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Файл раздела',
                'verbose_name_plural': 'Файлы разделов',
            },
        ),
    ]
